export enum DatabaseTypes {
    MYSQL = 'mysql',
    POSTGRES = 'postgres',
    COCKROACHDB = 'cockroachdb',
    SAP = 'sap',
    MARIADB = 'mariadb',
    SQLITE = 'sqlite',
    CORDOVA = 'cordova',
    REACT_NATIVE = 'react-native',
    NATIVESCRIPT = 'nativescript',
    SQLJS = 'sqljs',
    ORACLE = 'oracle',
    MSSQL = 'mssql',
    MONGODB = 'mongodb',
    AURORA_DATA_API = 'aurora-data-api',
    AURORA_DATA_API_PG = 'aurora-data-api-pg',
    EXPO = 'expo',
    BETTER_SQLITE3 = 'better-sqlite3',
    CAPACITOR = 'capacitor',
  }